apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: market-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "market"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "050223"