apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '050223';
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '050223';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;